### ISSUE TITLE
当程序没有联网的时候会报错

### ISSUE THREAD

**Issue by z244370114** [xinghongfei/LookLook#11]
**第一个错误**
Process: com.looklook.xinghongfei.looklook, PID: 29789
                                                                                   java.lang.NullPointerException: Attempt to invoke 
virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
                                                                                       at com.looklook.xinghongfei.looklook.fragment.ZhihuFragment.checkConnectivity(ZhihuFragment.java:258)
                                                                                       at com.looklook.xinghongfei.looklook.fragment.ZhihuFragment.onCreateView(ZhihuFragment.java:63)

`public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        setRetainInstance(true);
        View view = inflater.inflate(R.layout.zhihu_fragment_layout, container, false);
        ButterKnife.inject(this, view); 原代码是，在没有初始化之前就调用了。checkConnectivity(view);所以报错。
        checkConnectivity(view);
        return view;
    }`
**第二个错误**
Caused by: java.lang.IllegalArgumentException: null NetworkCallback
                                                     at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:2298)
                                                     at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:2460)
                                                     at com.looklook.xinghongfei.looklook.fragment.ZhihuFragment.checkConnectivity(ZhihuFragment.java:271)
                                                     at com.looklook.xinghongfei.looklook.fragment.ZhihuFragment.onCreateView(ZhihuFragment.java:64)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
NetworkCallback，没有初始化。
如果我判断是否为null。在 onPause（）方法里面也会调用，在回到该界面的时候。也会报错。

**Comment by JerryMissTom** [comment]
我也遇到同样的问题，已经解决了。

**Comment by z244370114** [comment]
嗯嗯。

**Comment by JerryMissTom** [comment]
原仓库合并了新的提交，你可以看下，思路和我的不一样。但是都解决了此问题。
