### ISSUE TITLE
android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView

### ISSUE THREAD

**Issue by meijieman** [xinghongfei/LookLook#35]
huawei p6 api19 启动就报错

错误信息
android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                                       at com.looklook.xinghongfei.looklook.adapter.ZhihuAdapter.onCreateViewHolder(ZhihuAdapter.java:65)
                                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)

**Comment by xinghongfei** [comment]
之前这个bug应该是修复了，是什么时候clone的代码？

**Comment by meijieman** [comment]
就刚才，使用 mate8 就ok api23
华为虚拟键盘没有做适配

**Comment by wanghong123qq** [comment]
The inflate exception is not actually the problem, but really comes from another deeper issue in your layout that is then wrapped in an InflateException. A common issue is an out of memory exception when trying to inflate an imageview loading a drawable resource. If one of this resources has a high pixel resolution it would take a lot of memory causing then an inflate exception.
你好请问一下vivo xplay3s出现这个问题怎么解决

**Comment by liuwenjun1361678** [comment]
@xinghongfei 这个问题感觉没解决到呢

**Comment by liuwenjun1361678** [comment]
@xinghongfei   api是不是有要求？
