### ISSUE TITLE
新clone下来的代码 报空指针错误

### ISSUE THREAD

**Issue by ghost** [xinghongfei/LookLook#37]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.looklook.xinghongfei.looklook, PID: 2442
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.looklook.xinghongfei.looklook.bean.news.NewsDetailBean.getBody()' on a null object reference
                      at com.looklook.xinghongfei.looklook.Activity.TopNewsDescribeActivity.upListItem(TopNewsDescribeActivity.java:395)
                      at com.looklook.xinghongfei.looklook.presenter.implPresenter.TopNewsDesPresenterImpl$1.onSuccess(TopNewsDesPresenterImpl.java:37)
                      at com.looklook.xinghongfei.looklook.presenter.implPresenter.TopNewsDesPresenterImpl$1.onSuccess(TopNewsDesPresenterImpl.java:33)
                      at com.looklook.xinghongfei.looklook.util.OkHttpUtils$3.run(OkHttpUtils.java:106)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ghost** [comment]
跟网速有关吗
