### ISSUE TITLE
如果手机没装SD卡 是不是也会报错啊

### ISSUE THREAD

**Issue by ghost** [xinghongfei/LookLook#38]
11-12 17:17:16.923 4527-4527/com.looklook.xinghongfei.looklook W/System.err: java.io.FileNotFoundException: /storage/emulated/0/LookLook/1478971036923.jpg: open failed: ENOENT (No such file or directory)
11-12 17:17:16.923 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
11-12 17:17:16.923 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity.saveImage(MeiziPhotoDescribeActivity.java:126)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity.access$000(MeiziPhotoDescribeActivity.java:50)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity$2$1.onClick(MeiziPhotoDescribeActivity.java:109)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at libcore.io.Posix.open(Native Method)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
11-12 17:17:16.924 4527-4527/com.looklook.xinghongfei.looklook W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
11-12 17:17:16.925 4527-4527/com.looklook.xinghongfei.looklook W/System.err: 	... 12 more
11-12 17:17:16.935 4527-4527/com.looklook.xinghongfei.looklook D/AndroidRuntime: Shutting down VM
11-12 17:17:16.935 4527-4527/com.looklook.xinghongfei.looklook E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.looklook.xinghongfei.looklook, PID: 4527
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
                                                                                     at android.support.design.widget.Snackbar.<init>(Snackbar.java:185)
                                                                                     at android.support.design.widget.Snackbar.make(Snackbar.java:217)
                                                                                     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity.saveImage(MeiziPhotoDescribeActivity.java:134)
                                                                                     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity.access$000(MeiziPhotoDescribeActivity.java:50)
                                                                                     at com.looklook.xinghongfei.looklook.Activity.MeiziPhotoDescribeActivity$2$1.onClick(MeiziPhotoDescribeActivity.java:109)
                                                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by xinghongfei** [comment]
非常感谢，代码写的不够严谨。
